version: "3.9"

services:
  redis:
    image: redis:alpine
    container_name: cmx_recruitment_redis
    ports:
      - "5004:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: always

volumes:
  redis_data:
